apiVersion: v1
kind: Service
metadata:
  name: agenda-medica-service
spec: 
  type: NodePort
  selector:
    app: agenda-medica
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080